Task3
iryna-pantsialeyeva/freeit pull request #3
Opened 2022-06-19 22:14 UTC by iryna-pantsialeyeva

The first task3 pull request was closed. Please check this one.

2022-06-24 06:44 UTC, RomanKashenok requested changes

2022-06-24 06:44 UTC, RomanKashenok commented on src/task3/DigitDifferencesFinder.java
> +        String number = input.nextLine();
в целом решение имеет право на жизнь, но строка != числу )) так что надо бы тут все же бло число заюзать

2022-06-24 06:44 UTC, RomanKashenok commented on src/task3/DigitDifferencesFinder.java
> +        String number = input.nextLine();
проверить что число норм (нам подходит) и потом уже его разбирать как массив символов

2022-06-24 06:44 UTC, RomanKashenok commented on src/task3/ReverseNumberWriter.java
> +            System.out.println(number % 10 * 1000 + number % 100 / 10 * 100 + (number / 100) % 10 * 10 + number / 1000);
по сути ты дважды выполнила одну и ту же операцию. Давай выполним её один раз и результат запишем в переменную, а уже переменную потом будем использовать сколько надо раз

2022-06-24 06:44 UTC, RomanKashenok commented on src/task3/SecondsCounter.java
> +        int secondsInWeek = 604800;
а если я попрошу добавить месяцы/годы/десятилетия? Придется руками счиатть? А если 6,5 недель? 
Давай отталкиваться от того, что знаем точно - в минуте 60 секунд, в часу 60 минут, в сутках 24 часа и т.д.

2022-06-27 14:05 UTC, iryna-pantsialeyeva commented on src/task3/ReverseNumberWriter.java
> +            System.out.println(number % 10 * 1000 + number % 100 / 10 * 100 + (number / 100) % 10 * 10 + number / 1000);
Не совсем поняла комментарий. Прошу прояснить. 17я и 19я строки в моем решении - варианты вывода результата таски, поскольку из условия непонятно, как выводить числа, заканчивающиеся на один или более 0.

2022-06-27 14:05 UTC, iryna-pantsialeyeva commented on src/task3/DigitDifferencesFinder.java
> +        String number = input.nextLine();
Done

2022-06-30 09:57 UTC, RomanKashenok requested changes

2022-06-30 09:57 UTC, RomanKashenok commented on src/task3/ReverseNumberWriter.java
> +            System.out.println(number % 10 * 1000 + number % 100 / 10 * 100 + (number / 100) % 10 * 10 + number / 1000);
number % 100 / 10
вот это вот, например, как я вижу, вычисляется несколько раз

2022-07-01 18:54 UTC, iryna-pantsialeyeva commented on src/task3/ReverseNumberWriter.java
> +            System.out.println(number % 10 * 1000 + number % 100 / 10 * 100 + (number / 100) % 10 * 10 + number / 1000);
Done. Огромное спасибо, +10 к code readability.

2022-07-01 19:51 UTC, iryna-pantsialeyeva commented on src/task3/SecondsCounter.java
> +        int secondsInWeek = 604800;
Done.

2022-07-03 08:15 UTC, closed without merging