Task4(homework4)
iryna-pantsialeyeva/freeit pull request #4
Opened 2022-06-23 22:30 UTC by iryna-pantsialeyeva

I kindly ask you to review my code.
Please don't merge this pull request.

2022-06-27 15:00 UTC, i-velichko commented on src/task4/Invitation.java
> +        System.out.print("Enter your sex (male of female): ");
In this implementation I don't see the reason of this question. The choice does not affect further answers in any way.

2022-06-30 10:11 UTC, RomanKashenok requested changes

2022-06-30 10:11 UTC, RomanKashenok commented on src/task3/SecondsCounter.java
> +                secondsInDay) % secondsInHour) % secondsInMinute);
переиспользуй свои вычисления. И сделай вывод более понятным (хотя бы как в примере)

2022-06-30 10:11 UTC, RomanKashenok commented on src/task3/ReverseNumberWriter.java
> +            System.out.println(number % 10 * 1000 + number % 100 / 10 * 100 + (number / 100) % 10 * 10 + number / 1000);
это я уже где-то комментировал

2022-06-30 10:11 UTC, RomanKashenok commented on src/task3/DigitDifferencesFinder.java
> +        }
где-то уже видел

2022-06-30 10:11 UTC, RomanKashenok commented on src/task4/FiveWayToCreateString.java
> +        StringBuilder string4 = new StringBuilder("4th way to create a string");
это не строка

2022-06-30 10:11 UTC, RomanKashenok commented on src/task4/FiveWayToCreateString.java
> +        String string5 = string4.replace(0, 2, "5th").toString();
ладно )

2022-06-30 10:11 UTC, RomanKashenok commented on src/task4/Invitation.java
> +        System.out.print("Enter your sex (male of female): ");
так а на строке 22?

2022-06-30 10:11 UTC, RomanKashenok commented on src/task4/MonthsAndSeason.java
> +            case "January":
давай объединим case с совпадающими выводами

2022-07-01 20:31 UTC, iryna-pantsialeyeva commented on src/task3/DigitDifferencesFinder.java
> +        }
Сорри. Неправильно создавался branch (не в main), потому подтянулись классы из pachage Task3. 
Прошу не обращать на них внимание. 
Последние таски создавались правильно - из мастера.

2022-07-01 20:37 UTC, iryna-pantsialeyeva commented on src/task3/ReverseNumberWriter.java
> +            System.out.println(number % 10 * 1000 + number % 100 / 10 * 100 + (number / 100) % 10 * 10 + number / 1000);
Прошу не оценивать таски из package Task3, вложенные в branch Task4. Причина - в комментарии к классу DigitDifferencesFinder.

2022-07-01 20:39 UTC, iryna-pantsialeyeva commented on src/task3/SecondsCounter.java
> +                secondsInDay) % secondsInHour) % secondsInMinute);
Прошу не оценивать таски из package Task3, вложенные в branch Task4. Причина - в комментарии к классу DigitDifferencesFinder.

2022-07-01 21:02 UTC, iryna-pantsialeyeva commented on src/task4/Invitation.java
> +        System.out.print("Enter your sex (male of female): ");
The choise of sort of drinks depends on the value of variable "sex".

2022-07-01 21:59 UTC, iryna-pantsialeyeva commented on src/task4/MonthsAndSeason.java
> +            case "January":
Done.

2022-07-02 17:57 UTC, iryna-pantsialeyeva commented on src/task4/FiveWayToCreateString.java
> +        StringBuilder string4 = new StringBuilder("4th way to create a string");
Done.
Добавила еще 1 способ, т.к. StringBuilder сам по себе строку не создает (а создает экземпляр своего класса).

2022-07-02 20:25 UTC, iryna-pantsialeyeva commented on src/task3/ReverseNumberWriter.java
> +            System.out.println(number % 10 * 1000 + number % 100 / 10 * 100 + (number / 100) % 10 * 10 + number / 1000);
По договоренности подтянула сюда решение из task3.

2022-07-02 20:27 UTC, iryna-pantsialeyeva commented on src/task3/SecondsCounter.java
> +                secondsInDay) % secondsInHour) % secondsInMinute);
По договоренности подтянула сюда решение из task3.

2022-07-02 20:28 UTC, iryna-pantsialeyeva commented on src/task3/DigitDifferencesFinder.java
> +        }
По договоренности подтянула сюда решение из task3.

2022-07-07 11:54 UTC, RomanKashenok approved these changes

2022-07-26 16:10 UTC, merged