add homework5 (from Java Beginner Book [p.21, 24] and Excel file)
iryna-pantsialeyeva/freeit pull request #5
Opened 2022-06-27 13:45 UTC by iryna-pantsialeyeva

Please review my PR 

Note: I couldn't be able to resolve the frequency dictionary using of only arrays. I was tipped to use HashSet.

2022-06-30 10:04 UTC, RomanKashenok requested changes

2022-06-30 10:04 UTC, RomanKashenok commented on src/task5/FrequencyDictionary.java
> +        Set<String> wordSet = new HashSet<>();
мы же пока не знаем ничего про Set и про коллекции в общем. Давай обойдемся без них

2022-06-30 10:04 UTC, RomanKashenok commented on src/task5/GuessTheLetter.java
> +            Scanner sc = new Scanner(System.in);
на каждой итерации цикла ты создаешь новый сканер

2022-06-30 10:04 UTC, RomanKashenok commented on src/task5/SumDivisibleBy3Number.java
> +        System.out.println("Sum of the first of " + counter + " numbers divisible by 3 is equal to " + sum + ".");
не правильно работает (попробуй сумму первых 5 чисел, делящихся на 3) 3 6 9 12 15 - должно быть 45

2022-07-03 13:20 UTC, iryna-pantsialeyeva commented on src/task5/SumDivisibleBy3Number.java
> +        System.out.println("Sum of the first of " + counter + " numbers divisible by 3 is equal to " + sum + ".");
Исходный код написан для задачи "Найдите сумму первых n целых чисел, которые делятся на 3. Отсчет вести от числа n, введенного с консоли", т.к. в задаче не указано, от какого числа вести отсчет. 
По запросу добавлен второй вариант решения - для отсчета для первых **натуральных** чисел (от 1).

2022-07-03 13:40 UTC, iryna-pantsialeyeva commented on src/task5/GuessTheLetter.java
> +            Scanner sc = new Scanner(System.in);
Благодарю за замечание. Исправила (сканер вынесла из цикла).

2022-07-03 18:35 UTC, iryna-pantsialeyeva commented on src/task5/FrequencyDictionary.java
> +        Set<String> wordSet = new HashSet<>();
Переделано с использованием Matcher + Pattern.

2022-07-07 12:02 UTC, RomanKashenok approved these changes

2022-07-27 20:48 UTC, closed without merging